services:
  app:
    build: ./
    volumes:
      - .:/workdir
    ports:
      - 8500:8000
  db:
    image: mysql:8.3
    volumes:
      - .laravel_app/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    ports:
      - 3506:3306
